"""
ai_decision/prompt_builder.py
==============================
Builds prompts for Entry Validation and Exit Monitoring tasks.
"""

import json
from typing import List, Dict, Any
from ai_decision.schemas import (
    EntryRequest, PickItem, AlphaSignals, MarketContext, PortfolioContext,
    ExitRequest, PositionStateItem
)


class PromptBuilder:
    @staticmethod
    def get_system_prompt() -> str:
        return (
            "You are a Quantitative Trading Decision Layer for an intraday mean-reversion strategy.\n"
            "Your job is to validate stock picks and monitor active positions.\n"
            "You receive structured alpha signal data and market context.\n"
            "CRITICAL SIGNAL FEATURE DIRECTIONALITY RULES:\n"
            "- All technical alpha signals (P1 through P6, C1 through C3) are cross-sectionally z-scored and INVERTED for a LONG mean-reversion strategy.\n"
            "- POSITIVE z-score values (+0.5 to +3.0) represent STRONG LONG CONVICTION (e.g., positive P1_overnight_gap means the stock gapped DOWN overnight and is expected to revert UP; positive P2_prev_day_momentum means the stock dropped yesterday and is oversold; positive P4_relative_strength means underperformance expecting a bounce).\n"
            "- Do NOT interpret positive feature values as price momentum or gap ups. High positive z-score values mean high statistical probability of upward mean-reversion!\n"
            "Guidelines:\n"
            "1. The quantitative engine is your primary signal source. Validate signals based on overall score and feature agreement.\n"
            "2. For Entry Validation: Approve strong candidates ('BUY'), skip weak/flawed setups ('HOLD'), or adjust size ('REDUCE').\n"
            "3. For Exit Monitoring: Recommend 'HOLD', 'SELL', 'REDUCE', or 'TIGHTEN_STOPS' for active positions.\n"
            "4. Respond STRICTLY with valid JSON matching the requested schema. Do NOT include markdown codeblocks or extra text."
        )

    @staticmethod
    def build_entry_prompt(
        picks: List[Dict[str, Any]],
        market_info: Dict[str, Any],
        portfolio_info: Dict[str, Any],
        timestamp_str: str,
    ) -> str:
        pick_items = []
        for p in picks:
            raw_signals = p.get("alpha_signals", {})
            # Merge from StockPicker's split signal dicts (preopen P1-P6 + confirm C1-C3)
            raw_signals.update(p.get("preopen_signals", {}))
            raw_signals.update(p.get("confirm_signals", {}))
            alpha = AlphaSignals(
                composite_score=p.get("composite_score", p.get("score", 0.0)),
                P1_overnight_gap=raw_signals.get("P1_overnight_gap"),
                P2_prev_day_momentum=raw_signals.get("P2_prev_day_momentum"),
                P3_volume_surge=raw_signals.get("P3_volume_surge"),
                P4_relative_strength=raw_signals.get("P4_relative_strength"),
                P5_range_expansion=raw_signals.get("P5_range_expansion"),
                P6_close_location=raw_signals.get("P6_close_location"),
                C1_opening_bar_reversal=raw_signals.get("C1_opening_bar_reversal"),
                C2_opening_volume=raw_signals.get("C2_opening_volume"),
                C3_gap_fill_speed=raw_signals.get("C3_gap_fill_speed"),
            )
            pick_items.append(
                PickItem(
                    symbol=p["ticker"],
                    entry_price=float(p.get("entry_price", 0.0)),
                    proposed_shares=int(p.get("shares", 0)),
                    group=p.get("group", "volatile"),
                    atr_value=p.get("atr_value"),
                    alpha_signals=alpha,
                )
            )

        req = EntryRequest(
            task="entry_validation",
            timestamp=timestamp_str,
            market=MarketContext(
                index_ticker=market_info.get("index_ticker", "QQQ"),
                index_price=market_info.get("index_price"),
                index_intraday_return_pct=market_info.get("index_intraday_return_pct"),
                market_tz=market_info.get("market_tz", "US/Eastern"),
            ),
            portfolio=PortfolioContext(
                capital=float(portfolio_info.get("capital", 100000)),
                existing_positions=int(portfolio_info.get("existing_positions", 0)),
                current_exposure_pct=float(portfolio_info.get("current_exposure_pct", 0.0)),
            ),
            picks=pick_items,
        )

        user_msg = (
            f"Analyze the following stock picks generated by the 9-feature alpha engine and return an EntryResponse JSON.\n"
            f"Required Output JSON format:\n"
            f'{{\n  "decisions": [\n    {{\n      "symbol": "AAPL",\n      "action": "BUY",\n      "confidence": 90,\n      "position_multiplier": 1.0,\n      "reasoning": ["Feature agreement", "Strong gap fill"]\n    }}\n  ]\n}}\n\n'
            f"Input Data:\n{req.model_dump_json(indent=2)}"
        )
        return user_msg

    @staticmethod
    def build_exit_prompt(
        tracking_states: Dict[str, Any],
        market_info: Dict[str, Any],
        portfolio_info: Dict[str, Any],
        timestamp_str: str,
    ) -> str:
        pos_items = []
        for ticker, state in tracking_states.items():
            if not state.get("active"):
                continue
            entry_px = float(state.get("entry_price", 1.0))
            curr_px = float(state.get("current_price", entry_px))
            pnl_pct = ((curr_px - entry_px) / entry_px) * 100.0 if entry_px > 0 else 0.0
            
            pos_items.append(
                PositionStateItem(
                    symbol=ticker,
                    entry_price=entry_px,
                    current_price=curr_px,
                    bar_high=float(state.get("bar_high", curr_px)),
                    bar_low=float(state.get("bar_low", curr_px)),
                    qty=int(state.get("qty", 0)),
                    pnl_pct=round(pnl_pct, 2),
                    high_water=float(state.get("high_water", curr_px)),
                    minutes_held=round(float(state.get("minutes_held", 0.0)), 1),
                    sl1_done=bool(state.get("sl1_done", False)),
                    pt1_done=bool(state.get("pt1_done", False)),
                    atr_value=state.get("atr_value"),
                )
            )

        req = ExitRequest(
            task="exit_validation",
            timestamp=timestamp_str,
            market=MarketContext(
                index_ticker=market_info.get("index_ticker", "QQQ"),
                index_price=market_info.get("index_price"),
                index_intraday_return_pct=market_info.get("index_intraday_return_pct"),
                market_tz=market_info.get("market_tz", "US/Eastern"),
            ),
            portfolio=PortfolioContext(
                capital=float(portfolio_info.get("capital", 100000)),
                existing_positions=len(pos_items),
                current_exposure_pct=float(portfolio_info.get("current_exposure_pct", 0.0)),
            ),
            positions=pos_items,
        )

        user_msg = (
            f"Analyze the active intraday positions and return an ExitResponse JSON.\n"
            f"Allowed actions: HOLD, SELL, REDUCE, TIGHTEN_STOPS.\n"
            f"Required Output JSON format:\n"
            f'{{\n  "exit_decisions": [\n    {{\n      "symbol": "AAPL",\n      "action": "HOLD",\n      "confidence": 85,\n      "adjusted_trail_trigger": null,\n      "reasoning": ["Within expected range"]\n    }}\n  ]\n}}\n\n'
            f"Input Data:\n{req.model_dump_json(indent=2)}"
        )
        return user_msg
